/**
 * Mock Movie Data
 * Static movie data for MatrixFlix with high-quality guaranteed Unsplash images.
 */

import { Movie, MovieDetails, Video } from './tmdb';

export const MOCK_MOVIES: Movie[] = [
    {
        id: 1,
        title: "Cyber Neon: Genesis",
        original_title: "Cyber Neon: Genesis",
        overview: "In a world where digital consciousness is the only currency, a rogue hacker discovers a hidden code that could rewrite reality itself.",
        poster_path: "https://images.unsplash.com/photo-1626814026160-2237a95fc5a0?q=80&w=500&auto=format&fit=crop",
        backdrop_path: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?q=80&w=1000&auto=format&fit=crop",
        release_date: "2024-12-15",
        vote_average: 8.7,
        vote_count: 1240,
        popularity: 98.5,
        adult: false,
        genre_ids: [28, 878, 12],
        original_language: "en",
        video: false,
    },
    {
        id: 2,
        title: "The Silent Forest",
        original_title: "The Silent Forest",
        overview: "A group of explorers venture into a forest where no sound can be heard, only to find that the silence is hunting them.",
        poster_path: "https://images.unsplash.com/photo-1536440136628-849c177e76a1?q=80&w=500&auto=format&fit=crop",
        backdrop_path: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=1000&auto=format&fit=crop",
        release_date: "2024-10-20",
        vote_average: 7.4,
        vote_count: 856,
        popularity: 85.2,
        adult: false,
        genre_ids: [27, 9648],
        original_language: "en",
        video: false,
    },
    {
        id: 3,
        title: "Midnight in Tokyo",
        original_title: "Midnight in Tokyo",
        overview: "Under the neon lights of Shinjuku, two strangers find connection in a city that never sleeps and always watches.",
        poster_path: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?q=80&w=500&auto=format&fit=crop",
        backdrop_path: "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?q=80&w=1000&auto=format&fit=crop",
        release_date: "2024-11-10",
        vote_average: 8.2,
        vote_count: 520,
        popularity: 76.8,
        adult: false,
        genre_ids: [18, 10749],
        original_language: "en",
        video: false,
    },
    {
        id: 4,
        title: "The Last Astronaut",
        original_title: "The Last Astronaut",
        overview: "Abandoned on Mars after a failed evacuation, Sarah must reach the polar ice caps before her life support reaches 0%.",
        poster_path: "https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?q=80&w=500&auto=format&fit=crop",
        backdrop_path: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=1000&auto=format&fit=crop",
        release_date: "2025-01-05",
        vote_average: 9.1,
        vote_count: 450,
        popularity: 120.4,
        adult: false,
        genre_ids: [878, 18, 12],
        original_language: "en",
        video: false,
    },
    {
        id: 5,
        title: "Shadow of the Dragon",
        original_title: "Shadow of the Dragon",
        overview: "Ancient myths collide with modern weaponry when a temple is excavated in the heart of Hong Kong.",
        poster_path: "https://images.unsplash.com/photo-1531259683007-016a7b628fc3?q=80&w=500&auto=format&fit=crop",
        backdrop_path: "https://images.unsplash.com/photo-1514539079130-25950c84af65?q=80&w=1000&auto=format&fit=crop",
        release_date: "2024-09-12",
        vote_average: 6.8,
        vote_count: 1200,
        popularity: 92.1,
        adult: false,
        genre_ids: [28, 14],
        original_language: "en",
        video: false,
    },
    {
        id: 6,
        title: "Ocean's Whisper",
        original_title: "Ocean's Whisper",
        overview: "A marine biologist discovers a species of bioluminescent creatures that communicate through music.",
        poster_path: "https://images.unsplash.com/photo-1551244072-5d12893278ab?q=80&w=500&auto=format&fit=crop",
        backdrop_path: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=1000&auto=format&fit=crop",
        release_date: "2024-08-30",
        vote_average: 7.1,
        vote_count: 340,
        popularity: 54.5,
        adult: false,
        genre_ids: [99, 10751],
        original_language: "en",
        video: false,
    },
    {
        id: 7,
        title: "The Alchemist's Daughter",
        original_title: "The Alchemist's Daughter",
        overview: "In Victorian London, a young woman discovers her father's secret laboratory and the potion that can turn time backward.",
        poster_path: "https://images.unsplash.com/photo-1534447677768-be436bb09401?q=80&w=500&auto=format&fit=crop",
        backdrop_path: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=1000&auto=format&fit=crop",
        release_date: "2024-07-15",
        vote_average: 7.9,
        vote_count: 890,
        popularity: 63.2,
        adult: false,
        genre_ids: [14, 18, 9648],
        original_language: "en",
        video: false,
    },
    {
        id: 8,
        title: "Velocity",
        original_title: "Velocity",
        overview: "An underground street racer is forced to cooperate with the police to take down a international smuggling ring.",
        poster_path: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?q=80&w=500&auto=format&fit=crop",
        backdrop_path: "https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?q=80&w=1000&auto=format&fit=crop",
        release_date: "2024-06-01",
        vote_average: 6.5,
        vote_count: 1560,
        popularity: 110.5,
        adult: false,
        genre_ids: [28, 80],
        original_language: "en",
        video: false,
    }
];

export const MOCK_TV_SHOWS: Movie[] = [
    {
        id: 101,
        title: "Signal Lost",
        original_title: "Signal Lost",
        overview: "When a strange radio signal is detected from the moon, a team of scientists must decrypt it before the government shuts them down.",
        poster_path: "https://images.unsplash.com/photo-1550684848-fac1c5b4e853?q=80&w=500&auto=format&fit=crop",
        backdrop_path: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=1000&auto=format&fit=crop",
        release_date: "2023-05-12",
        vote_average: 8.9,
        vote_count: 2300,
        popularity: 150.5,
        adult: false,
        genre_ids: [878, 9648],
        original_language: "en",
        video: false,
    },
    {
        id: 102,
        title: "The Chef's Secret",
        original_title: "The Chef's Secret",
        overview: "In the high-stakes world of fine dining, a young apprentice discovers her mentor is hiding more than just recipes.",
        poster_path: "https://images.unsplash.com/photo-1556910103-1c02745aae4d?q=80&w=500&auto=format&fit=crop",
        backdrop_path: "https://images.unsplash.com/photo-1556910111-a3aa7ccf7690?q=80&w=1000&auto=format&fit=crop",
        release_date: "2024-02-01",
        vote_average: 7.8,
        vote_count: 450,
        popularity: 65.2,
        adult: false,
        genre_ids: [18, 35],
        original_language: "en",
        video: false,
    },
    {
        id: 103,
        title: "Emerald Peak",
        original_title: "Emerald Peak",
        overview: "A small-town detective investigates a series of disappearances near a luxury mountain resort.",
        poster_path: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?q=80&w=500&auto=format&fit=crop",
        backdrop_path: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?q=80&w=1000&auto=format&fit=crop",
        release_date: "2023-11-20",
        vote_average: 8.5,
        vote_count: 1200,
        popularity: 88.4,
        adult: false,
        genre_ids: [9648, 80],
        original_language: "en",
        video: false,
    },
    {
        id: 104,
        title: "Neon Nights",
        original_title: "Neon Nights",
        overview: "In a futuristic megalopolis, a low-level enforcer finds himself caught in a conspiracy that goes to the very top.",
        poster_path: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?q=80&w=500&auto=format&fit=crop",
        backdrop_path: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?q=80&w=1000&auto=format&fit=crop",
        release_date: "2024-03-15",
        vote_average: 8.2,
        vote_count: 780,
        popularity: 95.1,
        adult: false,
        genre_ids: [28, 878],
        original_language: "en",
        video: false,
    }
];

export const MOCK_MY_LIST: Movie[] = MOCK_MOVIES.slice(0, 4).concat(MOCK_TV_SHOWS.slice(0, 1));

export const ALL_CONTENT = [...MOCK_MOVIES, ...MOCK_TV_SHOWS];

export const MOCK_GENRES = [
    { id: 28, name: "Action" },
    { id: 12, name: "Adventure" },
    { id: 16, name: "Animation" },
    { id: 35, name: "Comedy" },
    { id: 80, name: "Crime" },
    { id: 99, name: "Documentary" },
    { id: 18, name: "Drama" },
    { id: 10751, name: "Family" },
    { id: 14, name: "Fantasy" },
    { id: 36, name: "History" },
    { id: 27, name: "Horror" },
    { id: 10402, name: "Music" },
    { id: 9648, name: "Mystery" },
    { id: 10749, name: "Romance" },
    { id: 878, name: "Science Fiction" },
];

export const getMockMovieDetails = (id: number): MovieDetails => {
    const movie = ALL_CONTENT.find(m => m.id === id) || ALL_CONTENT[0];
    return {
        ...movie,
        budget: 50000000,
        genres: MOCK_GENRES.filter(g => movie.genre_ids.includes(g.id)),
        homepage: "https://matrixflix.com",
        imdb_id: "tt1234567",
        production_companies: [{ id: 1, logo_path: null, name: "Matrix Studios", origin_country: "US" }],
        production_countries: [{ iso_3166_1: "US", name: "United States of America" }],
        revenue: 150000000,
        runtime: 124,
        spoken_languages: [{ english_name: "English", iso_639_1: "en", name: "English" }],
        status: "Released",
        tagline: "Rewrite your reality.",
    };
};

export const MOCK_CREDITS = {
    cast: [
        { id: 1, name: "John Wick", character: "Neo", profile_path: null, order: 1 },
        { id: 2, name: "Carrie-Anne Moss", character: "Trinity", profile_path: null, order: 2 },
        { id: 3, name: "Laurence Fishburne", character: "Morpheus", profile_path: null, order: 3 },
    ],
    crew: [
        { id: 1, name: "Lana Wachowski", job: "Director", department: "Directing", profile_path: null },
    ]
};

export const MOCK_VIDEOS: Video[] = [
    {
        id: "1",
        key: "dQw4w9WgXcQ",
        name: "Official Trailer",
        site: "YouTube",
        size: 1080,
        type: "Trailer",
        official: true,
        published_at: "2024-01-01",
    }
];
